import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';

const root = fileURLToPath(new URL('../', import.meta.url));
const plain = line => line.replace(/^\s*#{1,6}\s*/, '').replace(/^\s*[-*]\s+/, '').trim().replace(/^\*\*(.+)\*\*$/, '$1');

export function parseAssignment(raw, source) {
  const sourceLines = raw.replace(/^\uFEFF/, '').split(/\r?\n/);
  const lines = sourceLines.map(plain);
  const first = lines.findIndex(line => /^과제\s*\d+$/.test(line));
  if (first < 0) throw new Error(`${source}: 과제 번호를 찾을 수 없습니다.`);
  const number = Number(lines[first].match(/\d+/)[0]);
  const content = lines.slice(first + 1).filter(Boolean);
  const title = content[0];
  const time = content.find(line => line.startsWith('계획시간'))?.replace(/^계획시간\s*/, '') || '';
  const description = content.slice(1, content.indexOf('왜 이걸 하는가')).filter(line => !line.startsWith('계획시간')).join('\n');
  const groups = [];
  const seen = new Set();
  for (const [index, line] of lines.entries()) {
    const card = line.match(/^카드\s+(\d+)\s*[—–-]\s*(.+)$/);
    if (card) groups.push({ number: Number(card[1]), title: card[2], criteria: [] });
    else if (/^\s*####\s+/.test(sourceLines[index]) && lines.slice(index + 1).find(Boolean) === '하는 일') {
      groups.push({ number: groups.length + 1, title: line, criteria: [] });
    }
    const criterion = line.match(/^(T\d+-C\d+)\s+(.+)$/);
    if (!criterion) continue;
    if (!groups.length) throw new Error(`${source}: 카드 밖에 있는 기준 ${criterion[1]}`);
    const [, id, text] = criterion;
    if (Number(id.match(/^T(\d+)/)[1]) !== number || seen.has(id)) throw new Error(`${source}: 잘못되거나 중복된 기준 ${id}`);
    seen.add(id);
    groups.at(-1).criteria.push({ id, text });
  }
  if (!title || !groups.length || groups.some(group => !group.criteria.length)) throw new Error(`${source}: 제목 또는 통과 기준 누락`);
  return { number, title, time, description, source, groups, count: seen.size, raw };
}

export async function build() {
  const files = (await readdir(resolve(root, 'assignments'))).filter(file => file.endsWith('.txt'));
  const assignments = await Promise.all(files.map(async file => parseAssignment(await readFile(resolve(root, 'assignments', file), 'utf8'), file)));
  assignments.sort((a, b) => a.number - b.number);
  if (new Set(assignments.map(item => item.number)).size !== assignments.length) throw new Error('중복 과제 번호가 있습니다.');
  if (!assignments.length) throw new Error('과제 파일이 없습니다.');
  const resources = JSON.parse(await readFile(resolve(root, 'assignments/resources.json'), 'utf8'));
  for (const [number, resource] of Object.entries(resources)) {
    if (!assignments.some(item => item.number === Number(number))) throw new Error(`과제 ${number}: 자료의 과제가 없습니다.`);
    for (const link of resource.links) {
      if (!/^assets\/[a-zA-Z0-9_./() -]+$/.test(link.path) || link.path.split('/').includes('..')) throw new Error(`잘못된 자료 경로: ${link.path}`);
      await readFile(resolve(root, link.path));
    }
  }
  await writeFile(resolve(root, 'data.js'), `// Generated by scripts/build.mjs. Edit assignments/*.txt and resources.json instead.\nwindow.ASSIGNMENTS = ${JSON.stringify(assignments, null, 2)};\nwindow.ASSIGNMENT_RESOURCES = ${JSON.stringify(resources, null, 2)};\n`);
  let html = await readFile(resolve(root, 'index.html'), 'utf8');
  for (const asset of ['styles.css', 'data.js', 'app.js']) {
    const digest = createHash('sha256').update(await readFile(resolve(root, asset))).digest('hex').slice(0, 12);
    const pattern = new RegExp(`\\./${asset.replace('.', '\\.')}(?:\\?v=[a-f0-9]+)?`, 'g');
    html = html.replace(pattern, `./${asset}?v=${digest}`);
  }
  await writeFile(resolve(root, 'index.html'), html);
  console.log(assignments.map(item => `과제 ${item.number}: ${item.count}개 기준`).join('\n'));
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await build();
